### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by pradeeps** [reportportal/agent-python-behave#1]
WHen I try to execute the features folder, I see No module named 'ConfigParser' when I try to execute.

In py3, ConfigParser is changed to configparser for pep8 compliance. So I changed the import to to use configparser  in rp_driver.py. then I get another import error:

ImportError: cannot import name 'ReportPortalServiceAsync' from 'reportportal_client' (C:\Users\username\.virtualenvs\agent-python-behave-74iEJSRJ\lib\site-packages\reportportal_client\__init__.py)

Am I missing something in here ?

**Comment by michaelpecan** [comment]
reportportal_client version 5 and above ReportPortalServiceAsync changes to ReportPortalService

**Comment by iivanou** [comment]
Fixed in #3.
