### ISSUE TITLE
rp_agent is initiated only in before_all

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#10]
you initiated rp_agent as None and gave it value only in before_all that means that there is a warning on rp_Agent in all other methods cause there is a chance the value of rp_agent will be None (from behave there is no chance but as pythonic way it is wrong), my solution for this is to add the rp_Agent initialization to context as context is a global parameter for all behave methods.
context.rp_agent = BehaveAgent(cfg, create_rp_service(cfg))

**Comment by HardNorth** [comment]
@martsiushkou looks reasonable, could you please add?

**Comment by amartiushkov-ms** [comment]
ok, will do

**Comment by iivanou** [comment]
Resolved in #11.
