### ISSUE TITLE
 is launch_id is for existing id or to pass as id to system 

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#13]
hey,
I have a question if I pass launch _id as a param will it be the launch id of all the runs that I pass that id with? I want to know so I could use it for merging multiple  RP runs to one suite cause I run all my feature files in parallel (I trigger behave per feature_file I want to test)

**Comment by iivanou** [comment]
Hi. If you pass a launch_id through the command line. then all the tests will be reported into that launch. Otherwise, a new launch will be created.

**Comment by michaelpecan** [comment]
thanks

**Comment by michaelpecan** [comment]
@iivanou just checked it and it didn't happen, I passed a launch_id with the same id and it created different launches

**Comment by iivanou** [comment]
@michaelpecan Behave does not support running tests in parallel out of the box. How exactly do you run your tests? If you use some wrappers, so you need to make sure that the launch ID is passed to the behave command explicitly and not to your wrapper.

**Comment by michaelpecan** [comment]
@iivanou  i use jenkins for parallel feature files
here is an example of a command I run:
behave ./tests/users/admin_user_permissions.feature -D launch_name=test@stg -D project=pecan_automation -D launch_id=9acec0d4-5423-4f93-b8f1-58255bf3bd5b
i checked all of the runs have the same launch_id

**Comment by iivanou** [comment]
This is a bug.

**Comment by iivanou** [comment]
@michaelpecan Can you test changes from #14? Thanks.

**Comment by michaelpecan** [comment]
@iivanou I didn't write but the launch_id I passed in the example was generated by me, not by the report portal,  is it valide?

**Comment by iivanou** [comment]
@michaelpecan It is invalid. Launch ID should be generated by RP.

**Comment by michaelpecan** [comment]
@iivanou and is there a way for me to get it through the report portal behave cause from your code this attribute is protected ( self._launch_id) or I should implement the python agent?

**Comment by iivanou** [comment]
Use the template below. Just replace values for variables like endpoint, project, token and etc.
![image](https://user-images.githubusercontent.com/8349078/116044005-10eaa980-a679-11eb-993c-6f38b2fe6c2a.png)
