### ISSUE TITLE
 _log() takes from 4 to 7 positional arguments but 8 were given while using logging

### ISSUE THREAD

**Issue by haseebkhanniazi** [reportportal/agent-python-behave#15]
I am getting error while using logging in steps file. I am performing API based Testing

        File "/usr/lib/python3.6/logging/__init__.py", line 1308, in info
          self._log(INFO, msg, args, **kwargs)
        File "/venv/lib/python3.6/site-packages/behave_reportportal/logger.py", line 35, in _log
          super()._log(level, msg, args, exc_info, extra, stack_info, stacklevel)
      TypeError: _log() takes from 4 to 7 positional arguments but 8 were given

logger.py is excetly the same as in the package

Step.py is as follow

@step('a Client GETs a "{request_type}" market data request')
def step_impl(context, request_type):
    try:
        context.last_api_response = context.api_instance.xxxxx(_request_auth=_request_auth, type=request_type)
        context.log.info("log message")
        context.log.info("log message with attachment", file_to_attach="path_to_file")
        context.log.info("log message for launch", is_launch_log=True)
        context.log.info("log message for launch with attachment", file_to_attach="path_to_file", is_launch_log=True)

    except ApiException as e:
        context.last_api_exception = e
        print("Exception" % e)

**Comment by amartiushkov-ms** [comment]
Could you provide more details? It's difficult to understand which line of code leads to this error

**Comment by haseebkhanniazi** [comment]
i am getting error in the logger.py file whenever i add below code in the step.py file
context.log.info("log message")
context.log.info("log message with attachment", file_to_attach="path_to_file")
context.log.info("log message for launch", is_launch_log=True)
context.log.info("log message for launch with attachment", file_to_attach="path_to_file", is_launch_log=True)

Error
File "/venv/lib/python3.6/site-packages/behave_reportportal/logger.py", line 35, in _log
      super()._log(level, msg, args, exc_info, extra, stack_info, stacklevel)
  TypeError: _log() takes from 4 to 7 positional arguments but 8 were given


that is logger file

    def _log(
            self,
            level,
            msg,
            args,
            exc_info=None,
            extra=None,
            stack_info=False,
            stacklevel=1,
            file_to_attach=None,
            is_launch_log=False,
    ):
        if file_to_attach or is_launch_log:
            extra = extra or {}
            if file_to_attach:
                extra["file_to_attach"] = file_to_attach
            if is_launch_log:
                extra["is_launch_log"] = is_launch_log
        super()._log(level, msg, args, exc_info, extra, stack_info, stacklevel)


the above last code line throwing  the error

**Comment by amartiushkov-ms** [comment]
Actually, can not reproduce it. Here my test code https://github.com/martsiushkou/agent-python-behave/blob/798dc3b5834509000b301b44f8899e95f0772785/features/steps/calculator.py#L8 and I can not get an exception

**Comment by michaelpecan** [comment]
happens to me also

**Comment by michaelpecan** [comment]
the issue is with "logging.setLoggerClass(RPLogger)"
once you initiated this all new loggers will be created as RPLogger and that is the issue cause   RPLogger  overrides _log with 8 parameters but the root logger is 4 params

**Comment by michaelpecan** [comment]
@martsiushkou @iivanou  fixed the issue on my side by patching the next code         
super()._log(level=level, msg=msg, args=args, exc_info=exc_info, extra=extra, stack_info=stack_info)
to summarize the issue is that you ask us to setlogger in enviroment file that from now on all loggers created in my automation will be created of type RPLogger but the way you guys ovveride the _log method is wrong as you are not passing argument that can be handled by **kwargs the example above fixed the original issue in this issue

**Comment by iivanou** [comment]
@michaelpecan, Actually, this error may occur only if you are running Python < 3.8. See [the signature of the _log method in Python 3.7](https://github.com/python/cpython/blob/3.7/Lib/logging/__init__.py#L1491) and [the signature of the _log method in Python 3.8](https://github.com/python/cpython/blob/3.8/Lib/logging/__init__.py#L1565). I believe @martsiushkou tried to reproduce it with Python 3.8. The reason why we do not catch this in unit tests is that we patch the _log method with mock.

@martsiushkou Can you fix it and improve unit tests?

**Comment by michaelpecan** [comment]
@iivanou cool you are right i am using 3.7

**Comment by amartiushkov-ms** [comment]
I will fix it later since I do not have enough time now

**Comment by iivanou** [comment]
@michaelpecan Can you try #18?

**Comment by michaelpecan** [comment]
@iivanou sure will update

**Comment by michaelpecan** [comment]
@iivanou works

**Comment by iivanou** [comment]
@michaelpecan Appreciate it. Merging...

**Comment by haseebkhanniazi** [comment]
Thanks guys.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
