### ISSUE TITLE
RPlogger overrrides logger library

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#16]
hey,
after we updated to last version my test broke because 
 RPLogger(Logger):
    """RPLogger class for logging tests."""

    def __init__(self, name, level=NOTSET):
        """
        Initialize RPLogger instance.

        :param name:  logger name
        :param level: level of logs
        """
        super().__init__(name, level=level)

    def _log(
        self,
        level,
        msg,
        args,
        exc_info=None,
        extra=None,
        stack_info=False,
        stacklevel=1,
        file_to_attach=None,
        is_launch_log=False,
    ):
        if file_to_attach or is_launch_log:
            extra = extra or {}
            if file_to_attach:
                extra["file_to_attach"] = file_to_attach
            if is_launch_log:
                extra["is_launch_log"] = is_launch_log
        super()._log(level, msg, args, exc_info, extra, stack_info, stacklevel)

this code overrides _log method in logger module, and other modules use it too (like selenium) and because of that I am getting an exception TypeError: _log() takes from 4 to 7 positional arguments but 8 were given.
you shouldn't ovveride the log of logger as my project and other modules will want to use it not only with the same signature of report portal

**Comment by iivanou** [comment]
This code overwrites _log method only for instances of the RPLogger class.

**Comment by michaelpecan** [comment]
@iivanou I can show you that the way you guys recommended implementing it in the environment file affects all of them

**Comment by iivanou** [comment]
Sure...

**Comment by michaelpecan** [comment]
@iivanou found the issue in the webdriver-manager library they do 
 _logger = logging.getLogger(name)

        handler = logging.StreamHandler()
        formatter = logging.Formatter(formatter)
        handler.setFormatter(formatter)
        _logger.addHandler(handler)
        _logger.setLevel(level)
        loggers[name] = _logger
        _logger.info(text)
because RPLogger is the only one because i am using logger that comes by default  in logger library so they catch the rp one in this line of code "logging.getLogger(name)" and use it.
will open a ticket for them thanks
