### ISSUE TITLE
step exception args are empty

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#17]
sometimes step exception args is without info and you guys do 
        if step.exception:
            **message.append(", ".join(step.exception.args))**
maybe better check if step.exception.args has data?
this is an example of what i have 
step.exception.args = ('', None, None)
but step.exception = TimeoutException

**Comment by michaelpecan** [comment]
@iivanou can you please look into this issue also?

**Comment by michaelpecan** [comment]
@martsiushkou can you help? even with a workaround for now

**Comment by amartiushkov-ms** [comment]
I will try to fix it in scope of the day

**Comment by michaelpecan** [comment]
thanks
