### ISSUE TITLE
 HOOK-ERROR in after_step

### ISSUE THREAD

**Issue by taruntechno** [reportportal/agent-python-behave#21]
Copied the environment.py file that you refered in installation instructions.

When running behave command seeing the following issue:

Captured stdout:
      HOOK-ERROR in after_step: TypeError: sequence item 1: expected str instance, list found

**Comment by netolyrg** [comment]
+1

**Comment by netolyrg** [comment]
@taruntechno I found fast solution, before context.rp_agent.finish_step(...):
```python
if step.exception and any(step.exception.args):
    step.exception.args = [str(arg) for arg in step.exception.args if arg]
```

This happens coz in some exceptions there are args with list, not str

**Comment by michaelpecan** [comment]
@taruntechno had the same issue https://github.com/reportportal/agent-python-behave/issues/17 they fixed it but they didn't release a new version

**Comment by netolyrg** [comment]
@michaelpecan fix will not work if args contains list as item, e.g. `args=["one", None, ["1", "2", "3"]]`

**Comment by michaelpecan** [comment]
@netolyrg thanks

**Comment by HardNorth** [comment]
Can someone create a PR for that?

**Comment by netolyrg** [comment]
I can

**Comment by netolyrg** [comment]
@HardNorth done https://github.com/reportportal/agent-python-behave/pull/22

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-python-behave/releases/tag/1.0.1
