### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#5]
@martsiushkou   thanks for making this project live looks really easy to implement, you have a broken link in the link to environment file 
1. forgot '/' before blob
2. change main to master
another question are you going to upload this repo to pypi?

**Comment by amartiushkov-ms** [comment]
@michaelpecan Thanks for comment, I updated the link in readme file.  Regarding the uploading to pypi - I will reply later

**Comment by iivanou** [comment]
@michaelpecan This project will be available on PyPi soon.
