### ISSUE TITLE
add screenshot on failed ui scenario test

### ISSUE THREAD

**Issue by michaelpecan** [reportportal/agent-python-behave#9]
hey,
I didn't find a way to add a screenshot and from looking in the code I see that you only store the exception log.

**Comment by HardNorth** [comment]
@martsiushkou Looks legit, could you please add a log method which accepts images?

**Comment by amartiushkov-ms** [comment]
@michaelpecan @HardNorth It's possible to attach any kind of files via `post_log` method. For example:

`rp_agent.post_log("some message", level="INFO", file_to_attach="path_to_file")`

But if we talk about special feature to take screenshot if test is failed and attach it to RP, I am not sure that it is responsibility of the Agent. It's easy to implement it in `after_scenario` function and attach it via `post_log` method. What do you think?

**Comment by michaelpecan** [comment]
@martsiushkou cool thanks but how can I add it as part of the failed scenario? cause now it means I need to add in mine code after scenario method to check for failed scenario and attach the log. is this the desired behavior?

**Comment by amartiushkov-ms** [comment]
@michaelpecan I think it should look something like:
```
def after_scenario(context, scenario):
    if scenario.status.name == "failed":
        filepath = function_to_take_screenshot()
        context.rp_agent.post_log("comment", "INFO", file_to_attach=filepath)
    context.rp_agent.finish_scenario(context, scenario)
```

From my point of view Behave-Agent it's just wrapper for RP client and it provides functionality for user to send some data to RP. And since UI testing is just small part of testing process, I am not sure that Agent should have some special functionality for screenshots. And I think it's absolutely ok to make changes in `environment.py` file (for example to call `use_fixture` function for mapping  tags with fixtures).
Anyway it's not a big deal to add this functionality to agent and if @HardNorth will say to add it - I will do it. 
And also I will describe how to attach files in Readme file.

**Comment by HardNorth** [comment]
@martsiushkou Correct we are not a test tool, so we are not going to be responsible for taking screenshots. If there is a method already this is enough. It's also a good point to  include it into my examples.

@michaelpecan Yes, that's how it works in any other agent. We are not a magic lamp which does everything people want. You have to program behavior by yourself. Moreover it's literally impossible to guess what everyone wants. Someone needs screenshots, but some people test Rest API and need logs, etc.

**Comment by michaelpecan** [comment]
@martsiushkou I didn't think it is a big thing just wanted to understand if you have the capability of adding files my use case is for an image and if so maybe attaching to a test(in this case scenario) should be done without duplication of "if scenario.status.name == "failed": " one time on my side and one time on yours, but I accept your way also, so thanks for the quick response.
@HardNorth you are testing reporting tool a screenshot is a big part of info that should be passed to the report. not the only one I should have a generic way to enrich report with custom info that is only for me. I don't think you are a magic lamp I just suggested a feature, if you guys would have said you wouldn't do it I would implement it by myself. a feature issue in Github is just a suggestion you can mark it as won't do.
you guys shouldn't guess what people need that is the purpose of an open-source platform like Github that users will point to problems and features that they would like.
thank you guys both for the quick response and for this repo also

**Comment by NetanelMosheCohen** [comment]
CC @HardNorth @iivanou
